[WIP] refactor: splitted into individual submodules
terraform-ibm-modules/terraform-ibm-observability-instances pull request #219
Opened 2023-03-06 12:24 UTC by Soaib024

### Description

Splitted the observability module into individual components 

### Types of changes in this PR
https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/212

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code
- [ ] Refactor 

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-03-20 11:30 UTC, shemau requested changes
https://developer.hashicorp.com/terraform/language/modules/develop/structure suggests that sub modules are stored in a modules/ subdirectory. The presence of the README is also significant, if a module is considered internal, no README should be provided.

Would it be neater, now that there is a (sub-)module for logdna, activity tracker, and sysdig to have those modules exclude logdna_, at_, activity_tracker and sysdig_ from the variable names and output names. These clarifiers only have a purpose in the root module.

2023-03-20 11:30 UTC, shemau commented on version.tf
>      logdna = {
This is required, it is included in the documentation to expose the required version, it also implicitly required by all the modules.

https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.1/docs/rules/terraform_unused_required_providers.md

2023-03-21 16:03 UTC, Soaib024 commented
I have changed those variables name except activity_tracker_provision logdna_provision  and sysdig_provision  in submodules, I think having variable name as provision will not make much sense, also as submodule can be consumed individually we can keep those readmes as it won't cause harm anyway

2023-03-21 23:28 UTC, shemau submitted a review, later dismissed

2023-03-22 09:51 UTC, shemau approved these changes
LGTM

2023-03-22 10:02 UTC, merged

2023-03-22 10:12 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/releases/tag/v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: