feat: add access tags to resources created by the module
terraform-ibm-modules/terraform-ibm-observability-instances pull request #282
Opened 2023-05-05 21:51 UTC by MatthewLemmond

### Description
Adds access tags to the resource instances created by the module if they are passed

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [x] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content
Add ability to attach access tags to resources created by the module, consumers who want to use the access tags will need additional permissions for Tagging service at the Administrator level.

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-05-19 10:02 UTC, shemau submitted a review, later dismissed
Looks good.

2023-05-19 15:57 UTC, ocofaigh requested changes
what about the root level module. Wont it need different variables to pass down to the submodules for access tags?

2023-05-19 22:48 UTC, MatthewLemmond commented
Updated to take 3 access tag inputs for each of the different possible resources that could need the access management tags in the same way the normal tags are structured

2023-05-22 10:17 UTC, ocofaigh commented on variables.tf
> +  description = "A list of access tags to apply to the resources created by the module. For more information, see https://cloud.ibm.com/docs/account?topic=account-access-tags-tutorial."
`to the resources created by the module` -> `to the Activity Tracker instance created by the module`

2023-05-22 10:18 UTC, ocofaigh commented on variables.tf
> +  description = "A list of access tags to apply to the resources created by the module. For more information, see https://cloud.ibm.com/docs/account?topic=account-access-tags-tutorial."
`to the resources created by the module` -> `to the Sysdig instance created by the module`

2023-05-22 10:18 UTC, ocofaigh commented on variables.tf
> +  description = "A list of access tags to apply to the resources created by the module. For more information, see https://cloud.ibm.com/docs/account?topic=account-access-tags-tutorial."
`to the resources created by the module` -> `to the LogDNA instance created by the module`

2023-05-22 10:19 UTC, ocofaigh requested changes
see comments on updates to variable descriptions

2023-05-22 13:41 UTC, ocofaigh reviewed
Sorry @MatthewLemmond I just spotted something that you might address in this PR too please. See https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/282/files#r1200535256

2023-05-22 15:56 UTC, ocofaigh commented
Must be a bug somewhere? `Error: ResourceServiceInstanceDoesnotExist: Given service instance : "null" doesn't exist`

2023-05-22 16:34 UTC, MatthewLemmond commented
I found it, I capitalized `CRN` when moving to the LoadMapFromYaml function, should be good now.

2023-05-22 17:50 UTC, ocofaigh approved these changes

2023-05-22 17:50 UTC, ocofaigh approved these changes

2023-05-22 17:50 UTC, merged

2023-05-22 17:54 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.7.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/releases/tag/v2.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: