feat: Add support to create the atracker to COS s2s auth policy
terraform-ibm-modules/terraform-ibm-observability-instances pull request #433
Opened 2024-01-04 14:33 UTC by Aashiq-J

### Description

Issue: https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/421

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-01-04 14:34 UTC, Aashiq-J commented
/run pipeline

2024-01-04 14:38 UTC, ocofaigh requested changes
Thanks for picking this up @Aashiq-J - In the issue I mentioned:

The docs recommend the use s2s auth over IAM apikey auth (no apikey rotation to worry about) so we should update the [observability_at_event_routing example](https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/tree/main/examples/observability_at_event_routing) to use s2s for the COS target instead of apikey

Can we include that as part of this PR ?

2024-01-05 04:22 UTC, Aashiq-J commented
/run pipeline

2024-01-05 04:55 UTC, Aashiq-J commented
/run pipeline

2024-01-05 05:42 UTC, Aashiq-J commented
```
│     "Result": {
│         "details": "{\"code\":\"TooManyRequests\",\"message\":\"You have exceeded your request rate of 100 r/s.\"}",
│         "error_code": "RC-ServiceBrokerErrorResponse",
│         "message": "Please contact the Service Provider for this error. Service Broker returned error status code 429",
│         "status_code": 422,
│         "transaction_id": "bss-571264ea681f8bbb"
│     },
```
will run after sometime

2024-01-05 08:58 UTC, Aashiq-J commented
/run pipeline

2024-01-05 11:42 UTC, ocofaigh approved these changes

2024-01-05 11:45 UTC, ocofaigh commented on modules/activity_tracker/variables.tf
> +    service_to_service_enabled        = optional(bool, false)
I think this should default to `true` actually, since this is the recommended approach

2024-01-05 11:45 UTC, ocofaigh requested changes
@Aashiq-J sorry I just noticed 1 more thing. See https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/433/files#r1442781980

2024-01-05 11:47 UTC, ocofaigh commented on modules/activity_tracker/variables.tf
> +    skip_atracker_cos_iam_auth_policy = optional(bool, true)
oh and this should be false too since we are defaulting `service_to_service_enabled` to true

2024-01-05 11:47 UTC, ocofaigh commented on variables.tf
> +    service_to_service_enabled        = optional(bool, false)
same as https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/433/files#r1442781980

2024-01-05 11:47 UTC, ocofaigh commented on variables.tf
> +    skip_atracker_cos_iam_auth_policy = optional(bool, true)
same as https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/433/files#r1442783462

2024-01-05 12:22 UTC, Aashiq-J commented
/run pipeline

2024-01-05 15:01 UTC, ocofaigh approved these changes

2024-01-05 15:01 UTC, merged