feat: add cloud logs policies
terraform-ibm-modules/terraform-ibm-observability-instances pull request #600
Opened 2024-10-24 11:28 UTC by maheshwarishikha

### Description

Add cloud logs policies

### Release required?

Add cloud logs policies

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-10-24 11:30 UTC, maheshwarishikha commented
/run pipeline

2024-10-24 12:00 UTC, maheshwarishikha commented
/run pipeline

2024-10-24 13:19 UTC, maheshwarishikha commented
/run pipeline

2024-10-24 18:32 UTC, maheshwarishikha commented
/run pipeline

2024-10-25 08:45 UTC, maheshwarishikha commented
/run pipeline

2024-10-25 09:15 UTC, maheshwarishikha commented
This time PR failed in EN integration code - 
```
2024/10/25 09:00:55 Terraform apply | module.observability_instances.module.cloud_logs[0].ibm_logs_outgoing_webhook.en_integration["1"]: Creation complete after 4s [id=eu-de/e765aee9-9bd6-45f5-9493-cf0b875ffb80/968730df-7b2e-45fa-97bd-4155f2f61789]
 2024/10/25 09:00:55 Terraform apply | 
 2024/10/25 09:00:55 Terraform apply | Error: ---
 2024/10/25 09:00:55 Terraform apply | id: terraform-693866e6
 2024/10/25 09:00:55 Terraform apply | summary: 'CreateOutgoingWebhookWithContext failed: No authentication information in
 2024/10/25 09:00:55 Terraform apply |   RequestContext'
 2024/10/25 09:00:55 Terraform apply | severity: error
 2024/10/25 09:00:55 Terraform apply | resource: ibm_logs_outgoing_webhook
 2024/10/25 09:00:55 Terraform apply | operation: create
 2024/10/25 09:00:55 Terraform apply | component:
 2024/10/25 09:00:55 Terraform apply |   name: github.com/IBM-Cloud/terraform-provider-ibm
 2024/10/25 09:00:55 Terraform apply |   version: 1.70.1
 2024/10/25 09:00:55 Terraform apply | ---
 2024/10/25 09:00:55 Terraform apply | 
 2024/10/25 09:00:55 Terraform apply | 
 2024/10/25 09:00:55 Terraform apply |   with module.observability_instances.module.cloud_logs[0].ibm_logs_outgoing_webhook.en_integration["0"],
```

2024-10-25 10:01 UTC, ocofaigh requested changes
I suggest to support creating multiple policies by using 1 input variable that is a list of objects

2024-10-25 10:02 UTC, maheshwarishikha commented
> I suggest to support creating multiple policies by using 1 input variable that is a list of objects

sure, will update the code accordingly.

2024-10-28 09:02 UTC, maheshwarishikha commented
/run pipeline

2024-10-28 18:19 UTC, maheshwarishikha commented
/run pipeline

2024-10-29 09:26 UTC, ocofaigh requested changes
Some minor comments. I suggest that you add the policy to the advanced example instead of basic. Thats also the example we run in PR tests

2024-10-29 09:26 UTC, ocofaigh commented on variables.tf
> +variable "logs_policies_config" {
suggest to call this `cloud_logs_policies`. All the other cloud logs variables start with `cloud_logs_` so lets be consistent (note that logs_routing is a different service)

2024-10-29 09:26 UTC, ocofaigh commented on modules/cloud_logs/variables.tf
> +variable "logs_policies_config" {
maybe just call this `policies`

2024-10-29 09:26 UTC, ocofaigh commented on modules/cloud_logs/README.md
> +  # Create log policy
this usage needs to be update

2024-10-29 10:17 UTC, maheshwarishikha commented on modules/cloud_logs/variables.tf
> +variable "logs_policies_config" {
done

2024-10-29 10:17 UTC, maheshwarishikha commented on modules/cloud_logs/README.md
> +  # Create log policy
updated

2024-10-29 12:50 UTC, maheshwarishikha commented
PR failed with EN related issue - 
```
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: ╷
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ Error: ---
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ id: terraform-693866e6
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ summary: 'CreateOutgoingWebhookWithContext failed: No authentication information in
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │   RequestContext'
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ severity: error
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ resource: ibm_logs_outgoing_webhook
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ operation: create
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ component:
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │   name: github.com/IBM-Cloud/terraform-provider-ibm
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │   version: 1.70.1
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ ---
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ 
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ 
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │   with module.observability_instances.module.cloud_logs[0].ibm_logs_outgoing_webhook.en_integration["1"],
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │   on ../../modules/cloud_logs/main.tf line 109, in resource "ibm_logs_outgoing_webhook" "en_integration":
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │  109: resource "ibm_logs_outgoing_webhook" "en_integration" {
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: │ 
TestRunUpgradeExample 2024-10-29T10:28:06Z logger.go:66: ╵
TestRunUpgradeExample 2024-10-29T10:28:06Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; 
```

re-running...

2024-10-29 16:09 UTC, ocofaigh approved these changes

2024-10-29 16:09 UTC, merged

2024-10-29 16:10 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.2.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/releases/tag/v3.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: